### ISSUE TITLE
SPTarkov crashes to desktop before launching

### ISSUE THREAD

**Issue by Sweeper5** [cdozdil/OptiScaler#120]
I tested version 0.6.7-Final and this one will launch SPTarkov to the menu, but the moment you access 3D mode it crashes to desktop, however framegen isn't there.

Version 0.7.0-Pre66 crashes before even loading the game.
And it seems to be a fairly early crash as the OptiScaler.log is at 0 bytes and is completely empty.
Last string of errors from the Wine log is attached below.

I am running Arch Linux and the game via Lutris as the log hints at.
My GPU in question is a Nvidia GeForce 2080 Ti.
`
lutris-wrapper: Escape From Tarkov
Started initial process 260124 from gamemoderun mangohud /usr/bin/wine /home/sweeper/Games/escape_from_tarkov/drive_c/GAMES/Escape from Tarkov/SPT.Launcher.exe
Start monitoring process.
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
[2024-11-22 01:25:00.793] [info] Util::DllPath C:\GAMES\Escape from Tarkov\dxgi.dll
[2024-11-22 01:25:00.793] [info] Config::Reload Trying to load ini from: C:\GAMES\Escape from Tarkov\nvngx.ini
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Avalonia.OpenGL.Egl.EglInterface.DestroySurface(IntPtr, IntPtr)
   at Avalonia.OpenGL.Egl.EglSurface.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean)
   at System.Runtime.InteropServices.SafeHandle.Dispose()
   at Avalonia.OpenGL.Egl.EglGlPlatformSurface+RenderTarget.BeginDrawCore()
   at Avalonia.OpenGL.Egl.EglPlatformSurfaceRenderTargetBase.BeginDraw()
   at Avalonia.Skia.GlRenderTarget.BeginRenderingSession()
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(Boolean)
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore(Boolean)
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderReentrancySafe(Boolean)
   at Avalonia.Rendering.Composition.Server.ServerCompositor.Render(Boolean)
   at Avalonia.Rendering.RenderLoop.TimerTick(System.TimeSpan)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.TimerQueueTimer.Fire(Boolean)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
Initial process has exited (return code: 512)
[2024-11-22 01:25:12.151] [info] Util::DllPath C:\GAMES\Escape from Tarkov\dxgi.dll
[2024-11-22 01:25:12.151] [info] Config::Reload Trying to load ini from: C:\GAMES\Escape from Tarkov\nvngx.ini
wine: Unhandled page fault on execute access to 000000007869CDE0 at address 000000007869CDE0 (thread 0508), starting debugger...
0884:fixme:dbghelp:elf_search_auxv can't find symbol in module
0884:fixme:dbghelp:elf_search_auxv can't find symbol in module
0884:fixme:ver:GetCurrentPackageId (000000000021FEB0 0000000000000000): stub
07f4:fixme:ver:GetCurrentPackageId (000000000021FEB0 0000000000000000): stub
Monitored process exited.
Exit with return code 512
`

**Comment by January-0002** [comment]
It may not be of too much use, but on Windows, on SPT 3.10, it crashes as soon as you load up 3d with DLSS turned on. (possibly an incompatibility)
